### ISSUE TITLE
Context menu not clickable on OS X

### ISSUE THREAD

**Issue by cgruber** [oharaandrew314/TinkerTime#190]
Right-click (ctrl-click on mac) menu items are themselves not clickable.  

Env:
OS X 10.10 (Yosemite)
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)

Notes:
  * Unsure if this is my machine, a Mac thing, a Mac Java thing, a java-version thing or what. 
  * Menu-bar items are fine, this seems only to be a context-menu thing.

I'll dig more into this later, try with different java versions, etc., but I wanted to track it.

**Comment by oharaandrew314** [comment]
For some context, I develop on Java 7, but my default system VM is Java 8.  I cannot reproduce this on Windows Java 7 or 8.

**Comment by oharaandrew314** [comment]
TinkerTime uses the Nimbus Look-and-Feel.  There was a mac-specific issue in the past, where the "Ctrl" key was still used as the copy and past modifier key, rather than "command".

You could try to eliminate the Look-and-Feel as an issue source by removing the [code which activates it](https://github.com/oharaandrew314/TinkerTime/blob/master/src/aohara/tinkertime/views/TinkerFrame.java#L28-45)

**Comment by oharaandrew314** [comment]
@cgruber, can you try [this prototype](https://drive.google.com/open?id=0ByGq5aXm4AHQcDR5UzRENmFxeDA&authuser=0) to see if this fixes the issue?

**Comment by cgruber** [comment]
I'll take a peek later today or tomorrow.

**Comment by cgruber** [comment]
I'm sorry - I got massively derailed by end-of-quarter.  Trying it out.

**Comment by cgruber** [comment]
This prototype seems to have fixed the issue.

**Comment by oharaandrew314** [comment]
Perfect, thanks!
